# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ggrBza_UrMT3ur6dYQvYxqz90E3qii7z
"""

def crear_tablero():
    """Crea un tablero vacío de 3x3."""
    return [[" ", " ", " "] for _ in range(3)]

def imprimir_tablero(tablero):
    """Imprime el tablero en la consola."""
    for i in range(3):
        print(f"{tablero[i][0]}|{tablero[i][1]}|{tablero[i][2]}")
        if i < 2:
            print("-----")

def movimiento_jugador(tablero, jugador):
    """Permite al jugador humano hacer un movimiento."""
    while True:
        try:
            fila = int(input("Elige fila (0, 1, 2): "))
            columna = int(input("Elige columna (0, 1, 2): "))
            if 0 <= fila <= 2 and 0 <= columna <= 2:
                if tablero[fila][columna] == " ":
                    tablero[fila][columna] = jugador
                    break
                else:
                    print("¡Casilla ocupada! Intenta de nuevo.")
            else:
                print("Entrada inválida. Ingresa números entre 0 y 2.")
        except ValueError:
            print("Entrada inválida. Ingresa números enteros.")

def hay_ganador(tablero):
    """Verifica si hay un ganador."""
    # Verificar filas y columnas
    for i in range(3):
        if tablero[i][0] == tablero[i][1] == tablero[i][2] != " ":
            return True
        if tablero[0][i] == tablero[1][i] == tablero[2][i] != " ":
            return True

    # Verificar diagonales
    if tablero[0][0] == tablero[1][1] == tablero[2][2] != " ":
        return True
    if tablero[0][2] == tablero[1][1] == tablero[2][0] != " ":
        return True

    return False

def tablero_lleno(tablero):
    """Verifica si el tablero está lleno."""
    for fila in tablero:
        if " " in fila:
            return False
    return True

def juego_completo():
    """Ejecuta el juego completo del tres en raya."""
    tablero = crear_tablero()
    jugador_actual = "X"

    while True:
        imprimir_tablero(tablero)
        print(f"Turno de {jugador_actual}")
        movimiento_jugador(tablero, jugador_actual)

        if hay_ganador(tablero):
            imprimir_tablero(tablero)
            print(f"¡{jugador_actual} ha ganado!")
            break

        if tablero_lleno(tablero):
            imprimir_tablero(tablero)
            print("¡Empate!")
            break


        if jugador_actual == "X":
            jugador_actual = "O"
        else:
            jugador_actual = "X"


juego_completo()